### PR TITLE
add tests and syntax cleanup

### PR DESCRIPTION
**Pull request by ephraimschmitt**
First off, really great base to creating generative art. I wanted to use this as a base, but wanted to make some changes. I started by adding some tests around most of the functions (will add more later). I just made some basic syntax changes. Mostly just making the code simpler. I'm probably going to convert it to typescript as that what I like use. If you want I can push up those changes as well. Since I'm using this as as base I wanted to make sure to add as much value to you as I could. Any questions just let me know. Thanks

### CODE REVIEW

**Comment by ephraimschmitt** [comment]
Found a bug generating the attributes, working on fixing it now

**Comment by ephraimschmitt** [comment]
Ok, not sure that it is a bug. Seems like maybe the code has changed and the attributes no longer contain rarity?

**Comment by HashLips** [comment]
> First off, really great base to creating generative art. I wanted to use this as a base, but wanted to make some changes. I started by adding some tests around most of the functions (will add more later). I just made some basic syntax changes. Mostly just making the code simpler. I'm probably going to convert it to typescript as that what I like use. If you want I can push up those changes as well. Since I'm using this as as base I wanted to make sure to add as much value to you as I could. Any questions just let me know. Thanks

Hi, thank you for contributing to the project. I will read through the code and then we can include it.

**Comment by ephraimschmitt** [comment]
Added some changes to make it a little more functional and to make things easier to test.

**Pull request closed without merging**
